baseURL = "https://petermbenjamin.github.io"
languageCode = "en-us"
title = "Peter M. Benjamin"
DefaultContentLanguage = "en"
publishDir = "public/"
theme = "introduction" # https://github.com/vickylai/hugo-theme-introduction

[params]
themeStyle = "light"
favicon = "/img/fav.ico"
showRSSButton = true
fadeIn = false
fadeInIndex = true
dateFormat = "Jan 2, 2006"
email = "petermbenjamin@gmail.com"
customCSS = ["css/all.min.css"] # latest font-awesome v5.6.3

[params.home]
introHeight = "large"
showLatest = true
showAllPosts = true
numberOfProjectsToShow = 3
localTime = true
timeZone = "America/Los_Angeles"

[params.projects]
useTwoColumns = false

[params.share]
twitter = true
linkedin = true

[[params.social]]
url   = "https://twitter.com/petermbenjamin"
icon  = "twitter"
icon_pack = "fab"
[[params.social]]
url   = "https://github.com/petermbenjamin"
icon  = "github"
icon_pack = "fab"
[[params.social]]
url = "https://dev.to/petermbenjamin"
icon = "dev"
icon_pack = "fab"
[[params.social]]
url = "https://medium.com/@petermbenjamin"
icon = "medium"
icon_pack = "fab"
[[params.social]]
url = "https://keybase.io/pbenj"
icon = "keybase"
icon_pack = "fab"
[[params.social]]
url   = "https://linkedin.com/in/pmbenjamin"
icon  = "linkedin-in"
icon_pack = "fab"
[[params.social]]
url = "mailto:petermbenjamin@gmail.com"
icon = "envelope"
icon_pack = "fas"
