baseURL = "https://pbnj.dev"
languageCode = "en-us"
title = "Peter M. Benjamin"
DefaultContentLanguage = "en"
publishDir = "public/"
theme = "simple" # https://github.com/Xzya/simple-hugo-theme

copyright = "© 2019 — Peter M. Benjamin — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/blog/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 2

  # Footer
  [[menu.footer]]
    url = "https://github.com/petermbenjamin"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "RSS"
    weight = 2
  [[menu.footer]]
    url = "mailto:petermbenjamin@gmail.com"
    name = "Contact"
    weight = 3


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"
